network: SATRN
input_size:
  height: 48
  width: 192
SATRN:
  encoder:
    hidden_dim: 300
    filter_dim: 1200
    layer_num: 6
    head_num: 8

    shallower_cnn: True # shallow CNN
    adaptive_gate: True # A2DPE
    conv_ff: True # locality-aware feedforward
    separable_ff: True # only if conv_ff is True
  decoder:
    src_dim: 300
    hidden_dim: 128
    filter_dim: 512
    layer_num: 3
    head_num: 8

checkpoint: ""
prefix: "./log/satrn"

data:
  train:
    - "/opt/ml/input/data/train_dataset/gt.txt"
    # - /opt/ml/input/data/train_dataset/custom_train.txt # for experiments
  test:
    -
    # - /opt/ml/input/data/train_dataset/custom_test.txt # for experiments
  token_paths:
    - "/opt/ml/input/data/train_dataset/tokens.txt"  # 241 tokens
  dataset_proportions:  # proportion of data to take from train (not test)
    - 1.0
  random_split: True # if True, random split from train files
  test_proportions: 0.2 # only if random_split is True
  crop: True
  rgb: 1    # 3 for color, 1 for greyscale
  
batch_size: 16
num_workers: 8
num_epochs: 200
print_epochs: 1
dropout_rate: 0.1
teacher_forcing_ratio: 0.5
teacher_forcing_damp: 5e-3 # 0 to turn off
max_grad_norm: 2.0
seed: 1234
optimizer:
  optimizer: Adam # Adam, Adadelta
  lr: 5e-4 # 1e-4
  weight_decay: 1e-4
  selective_weight_decay: True
  is_cycle: True

patience: 10 # -1 for off
save_best_only: True

fp16: True

wandb:
  wandb: True
  run_name: ^____________^